apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sslcheck.fullname" . }}-config
  labels:
    {{- include "sslcheck.labels" . | nindent 4 }}
data:
  sslcheck.toml: |
    [log]
    verbose = true
    console = false
    [ssl]
    warnValidity = {{ .Values.sslExpiryThreshold.warning }}
    criticalValidity = {{ .Values.sslExpiryThreshold.critical }}
    {{- if ne .Values.slackHookUrl "" }}
    [slack]
    enabled = true
    hookUrl = {{ .Values.slackHookUrl | quote }}
    {{- end -}}
