apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "sslcheck.fullname" . }}
  labels:
    {{- include "sslcheck.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.schedule | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          serviceAccountName: {{ include "sslcheck.serviceAccountName" . }}
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}
          volumes:
          - name: config
            configMap:
              name: {{ include "sslcheck.fullname" . }}-config
          containers:
          - name: {{ .Chart.Name }}
            image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            args:
            {{- range .Values.hosts }}
            - --host={{ . }}
            {{- end }}
            volumeMounts:
            - name: config
              readOnly: true
              mountPath: /etc/sslcheck/sslcheck.toml
              subPath: sslcheck.toml
          restartPolicy: OnFailure
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
        {{- end }}
