{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sslcheck.serviceAccountName" . }}
  labels:
{{ include "sslcheck.labels" . | nindent 4 }}
{{- end -}}
