name: Publish Docker
on:
  push:
    tags:
      - v*
jobs:
  image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@v2.11
      with:
        name: soon/sslcheck
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: build/package/Dockerfile
        tag_names: true
